title = "• Home •"
# title of homepage

profile = "%APPDATA%\\Mozilla\\Firefox\\Profiles\\ety1761x.default-release-1"
# profile folder

bookmarks = "/"
# folder with categories
# %folder%/
#        dev/*
#        social/*
#        news/*